# If you change the DB name here, also change it in djangocon2014/settings/travis.py
before_script:
  - psql -c 'create database djangocon2014;' -U postgres
language: python
python:
  - "2.7"
env:
  - TOXENV=djangocon2014
install:
  - pip install -q tox==1.6.1
script:
  - tox -- --settings=djangocon2014.settings.travis
